-- MySQL Script generated by MySQL Workbench
-- vie 17 ago 2018 10:52:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Aluses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Aluses` ;

-- -----------------------------------------------------
-- Schema Aluses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aluses` DEFAULT CHARACTER SET utf8 ;
USE `Aluses` ;

-- -----------------------------------------------------
-- Table `Aluses`.`Crew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Crew` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Crew` (
  `idCrew` INT NOT NULL AUTO_INCREMENT,
  `dayStaying` INT NOT NULL,
  PRIMARY KEY (`idCrew`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluses`.`Discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Discount` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Discount` (
  `idDiscount` INT NOT NULL,
  `percentDiscount` INT NOT NULL,
  PRIMARY KEY (`idDiscount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluses`.`VIP_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`VIP_clients` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`VIP_clients` (
  `id_VIP_clients` INT NOT NULL AUTO_INCREMENT,
  `idDiscount` INT NOT NULL,
  PRIMARY KEY (`id_VIP_clients`),
  CONSTRAINT `fk_VIP_clients_Discount1`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `Aluses`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VIP_clients_Discount1_idx` ON `Aluses`.`VIP_clients` (`idDiscount` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Disabled_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Disabled_clients` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Disabled_clients` (
  `id_Disabled_clients` INT NOT NULL AUTO_INCREMENT,
  `idDiscount` INT NOT NULL,
  PRIMARY KEY (`id_Disabled_clients`),
  CONSTRAINT `fk_Disabled_clients_Discount1`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `Aluses`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Disabled_clients_Discount1_idx` ON `Aluses`.`Disabled_clients` (`idDiscount` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Normal_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Normal_clients` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Normal_clients` (
  `id_Normal_clients` INT NOT NULL AUTO_INCREMENT,
  `idDiscount` INT NOT NULL,
  PRIMARY KEY (`id_Normal_clients`),
  CONSTRAINT `fk_Normal_clients_Discount1`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `Aluses`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Normal_clients_Discount1_idx` ON `Aluses`.`Normal_clients` (`idDiscount` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Person` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_Crew` INT NULL,
  `id_VIP_clients` INT NULL,
  `id_Disabled_clients` INT NULL,
  `id_Normal_clients` INT NULL,
  PRIMARY KEY (`idPerson`),
  CONSTRAINT `fk_Person_CabinAssistants1`
    FOREIGN KEY (`id_Crew`)
    REFERENCES `Aluses`.`Crew` (`idCrew`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_VIP_clients1`
    FOREIGN KEY (`id_VIP_clients`)
    REFERENCES `Aluses`.`VIP_clients` (`id_VIP_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Disabled_clients1`
    FOREIGN KEY (`id_Disabled_clients`)
    REFERENCES `Aluses`.`Disabled_clients` (`id_Disabled_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Normal_clients1`
    FOREIGN KEY (`id_Normal_clients`)
    REFERENCES `Aluses`.`Normal_clients` (`id_Normal_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Person_CabinAssistants1_idx` ON `Aluses`.`Person` (`id_Crew` ASC);

CREATE INDEX `fk_Person_VIP_clients1_idx` ON `Aluses`.`Person` (`id_VIP_clients` ASC);

CREATE INDEX `fk_Person_Disabled_clients1_idx` ON `Aluses`.`Person` (`id_Disabled_clients` ASC);

CREATE INDEX `fk_Person_Normal_clients1_idx` ON `Aluses`.`Person` (`id_Normal_clients` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`PlaneModel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`PlaneModel` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`PlaneModel` (
  `code` VARCHAR(45) NOT NULL,
  `seatQuantity` INT NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluses`.`Plane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Plane` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Plane` (
  `idPlane` INT NOT NULL AUTO_INCREMENT,
  `modelCode` VARCHAR(45) NOT NULL,
  `constructionDay` DATE NOT NULL,
  PRIMARY KEY (`idPlane`),
  CONSTRAINT `fk_Plane_PlaneModel1`
    FOREIGN KEY (`modelCode`)
    REFERENCES `Aluses`.`PlaneModel` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plane_PlaneModel1_idx` ON `Aluses`.`Plane` (`modelCode` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Seats` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Seats` (
  `seatNumber` INT NOT NULL,
  `modelCode` VARCHAR(45) NOT NULL,
  `seatClass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seatNumber`),
  CONSTRAINT `fk_Seats_PlaneModel1`
    FOREIGN KEY (`modelCode`)
    REFERENCES `Aluses`.`PlaneModel` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seats_PlaneModel1_idx` ON `Aluses`.`Seats` (`modelCode` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Flight` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Flight` (
  `idFlight` INT NOT NULL AUTO_INCREMENT,
  `destination` VARCHAR(45) NOT NULL,
  `arrival` VARCHAR(45) NOT NULL,
  `idPlane` INT NOT NULL,
  PRIMARY KEY (`idFlight`),
  CONSTRAINT `fk_Flight_Plane1`
    FOREIGN KEY (`idPlane`)
    REFERENCES `Aluses`.`Plane` (`idPlane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Flight_Plane1_idx` ON `Aluses`.`Flight` (`idPlane` ASC);


-- -----------------------------------------------------
-- Table `Aluses`.`Flight_has_Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluses`.`Flight_has_Person` ;

CREATE TABLE IF NOT EXISTS `Aluses`.`Flight_has_Person` (
  `idFlight` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `seatNumber` INT NOT NULL,
  PRIMARY KEY (`idFlight`, `idPerson`),
  CONSTRAINT `fk_Flight_has_Person_Flight1`
    FOREIGN KEY (`idFlight`)
    REFERENCES `Aluses`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Person_Person1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `Aluses`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Person_Seats1`
    FOREIGN KEY (`seatNumber`)
    REFERENCES `Aluses`.`Seats` (`SeatNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Flight_has_Person_Person1_idx` ON `Aluses`.`Flight_has_Person` (`idPerson` ASC);

CREATE INDEX `fk_Flight_has_Person_Flight1_idx` ON `Aluses`.`Flight_has_Person` (`idFlight` ASC);

CREATE INDEX `fk_Flight_has_Person_Seats1_idx` ON `Aluses`.`Flight_has_Person` (`seatNumber` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
